pipeline:
  install:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm ci
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/ember-rdfa-editor-lblod-plugins
      tags: "${CI_COMMIT_TAG##v}"
      purge: true
    secrets: [ docker_username, docker_password ]
    # Pipeline level conditions aren't supported yet:
    # https://github.com/woodpecker-ci/woodpecker/issues/283
when:
  event: tag
  tag: v*
