steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/ember-rdfa-editor-lblod-plugins
      tags: '${CI_COMMIT_TAG##v}'
      purge: true
    secrets: [docker_username, docker_password]
when:
  event: tag
  ref: refs/tags/v*
