steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
  push-tagged-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: lblod/ember-rdfa-editor-lblod-plugins
      tags: '${CI_COMMIT_TAG##v}'
      purge: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
when:
  - event: tag
    ref: refs/tags/v*
