steps:
  changelog:
    image: danlynn/ember-cli:4.8.0
    commands:
      - git fetch origin master
      - git diff -wb --name-only origin/master..HEAD | grep CHANGELOG.md
    when:
      event: pull_request
      evaluate: 'not (CI_COMMIT_PULL_REQUEST_LABELS contains "dependabot")'
  install:
    image: danlynn/ember-cli:4.8.0
    commands:
      - npm ci
  # ember-try already runs ember test, so we don't need another test step
  lint-js:
    image: danlynn/ember-cli:4.8.0
    group: check
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:4.8.0
    group: check
    commands:
      - npm run lint:hbs
  test:
    image: danlynn/ember-cli:4.8.0
    group: check
    commands:
      - ember test
  precompile:
    image: danlynn/ember-cli:4.8.0
    commands:
      - ember ts:precompile


  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
    when:
      event: tag
      ref: refs/tags/v*

  push-tagged-build:
    image: plugins/docker
    settings:
      repo: lblod/ember-rdfa-editor-lblod-plugins
      tags: "${CI_COMMIT_TAG##v}"
      purge: true
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
      ref: refs/tags/v*
# according to docs, this also runs on prs targetting master
when:
  branch: [ master, hotfix/* ]
