steps:
  install:
    image: node:22-slim
    commands:
      - npm config set ignore-scripts true
      - npm i -g corepack@0.35
      - corepack enable
      - pnpm i --frozen-lockfile
  lint-js:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:js
  lint-hbs:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:hbs
  lint-prettier:
    image: node:22-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:prettier
  test:
    image: danlynn/ember-cli:6.7.2-node_22.19
    commands:
      - npm config set ignore-scripts true
      - npm i -g corepack@0.35
      - corepack enable
      - pnpm test:ember
  precompile:
    image: node:22-slim
    commands:
      - corepack enable
      - pnpm prepack
when:
  - evaluate: 'CI_PIPELINE_EVENT == "pull_request" && not (CI_COMMIT_PULL_REQUEST_LABELS contains "dependabot")'
