steps:
  install:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm i --frozen-lockfile
  lint-js:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:js
  lint-hbs:
    image: node:20-slim
    group: lint
    commands:
      - corepack enable
      - pnpm lint:hbs
  test:
    image: danlynn/ember-cli:4.12.1
    commands:
      - corepack enable
      - pnpm test:ember
  precompile:
    image: node:20-slim
    commands:
      - corepack enable
      - pnpm prepack
when:
  - evaluate: 'CI_PIPELINE_EVENT == "pull_request" && not (CI_COMMIT_PULL_REQUEST_LABELS contains "dependabot")'
